apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
  namespace: kubeedge
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: cloudcore
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: cloudcore
    spec:
      nodeSelector: # configure the nodeSelector here to directly schedule pods to specific nodes
        kubernetes.azure.com/cluster: MC_kubeedge_kubeedge_swedencentral
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kubeedge
                    operator: In
                    values:
                      - cloudcore
              topologyKey: kubernetes.io/hostname
      containers:
        - name: cloudcore
          image: kubeedge/cloudcore:v1.14.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 10000
              name: cloudhub
              protocol: TCP
            - containerPort: 10002
              name: cloudhub-https
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: conf
              mountPath: /etc/kubeedge/config
          env:
            - name: CLOUDCORE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLOUDCORE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
      serviceAccount: cloudcore
      serviceAccountName: cloudcore
      volumes:
        - name: conf
          configMap:
            name: cloudcore

