apiVersion: v1
kind: Pod
metadata:
  name: mnist1
spec:
  containers:
  - name: mnist1
    image: magiccpp1/mnist-arm32v7:01
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - name: edge-disk-volume
      mountPath: /app/disk
  hostAliases:
    - ip: "172.17.0.2"
      hostnames:
        - "mqtt"
  nodeSelector:
    kubernetes.io/hostname: raspberrypi
  volumes:
    - name: edge-disk-volume
      persistentVolumeClaim:
        claimName: edge-disk-claim

