apiVersion: v1
kind: Pod
metadata:
  name: mnist1
spec:
  containers:
  - name: mnist1
    image: magiccpp1/mnist-arm32v7:02
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - name: edge-disk-volume
      mountPath: /app/disk
    env:
    - name: STORAGE_PATH
      value: /app/disk
    - name: MQTT_IP
      value: 172.17.0.2
    - name: MQTT_TOPIC
      value: image_classification
  hostAliases:
    - ip: "172.17.0.2"
      hostnames:
        - "mqtt"
  nodeSelector:
    kubernetes.io/hostname: raspberrypi
  volumes:
    - name: edge-disk-volume
      persistentVolumeClaim:
        claimName: edge-disk-claim

