apiVersion: v1
kind: PersistentVolume
metadata:
  name: edge-disk-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/volume


